Fixes 194: Update with zero values in repository dao
content-services/content-sources-backend pull request #115
Opened 2022-09-27 15:16 UTC by rverdile

Previously, zero values were being used to indicate that a field should not be updated on `dao.Repository`. For example, if `Repository.Revision == ""`, don't update. Theoretically, if a Revision number was actually `""`, this value could not be updated. 

This PR introduces a `RepositoryUpdate` structure that uses pointers for all values. Using this, `nil` indicates "do not update", so that `dao.Repository` can now be updated with zero values.

One way to test this would be to host a local yum repo where you can change the revision number. Try changing it then removing it and you should see it update in the database accordingly, after introspection.

2022-09-27 21:00 UTC, jlsherrill commented
https://issues.redhat.com/browse/HMSCONTENT-194

2022-09-29 14:50 UTC, rverdile commented
rebased so now this includes package count

2022-10-03 09:18 UTC, avisiedo requested changes
One change change, and one suggestion which if agreed would need changes.

2022-10-03 17:54 UTC, rverdile commented on pkg/external_repos/introspect_test.go
> +	//mockRepoDao.Mock.AssertExpectations(t)
I probably commented this line by mistake

2022-10-03 17:58 UTC, rverdile commented on pkg/dao/repositories.go
> +
I'm not sure about only using the model layer for Repository. Even though it's not used in the handler/api layer, it is used in external_repos/introspect. That makes me think the separation should exist.

If we don't want to maintain both internal dao.Repository and dao.RepositoryUpdate structs, maybe I can just change dao.Repository to use all pointers and remove dao.RepositoryUpdate.

We should see what @jlsherrill thinks too.

2022-10-04 14:23 UTC, jlsherrill commented on pkg/dao/repositories.go
> +
@avisiedo i kinda get what you're saying, and we may want to collapse the model layer into the dao layer to better achieve this.  I've been thinking about proposing that.  However i think for this pr, we should just focus on fixing the issue at hand, and lets file another issue writing up the larger change.  Sound okay?

2022-10-11 13:47 UTC, avisiedo commented on pkg/dao/repositories.go
> +
sounds okay!

2022-10-11 13:49 UTC, avisiedo commented
:+1: lgtm

2022-10-11 14:06 UTC, merged